### ISSUE TITLE
Combined stream doesn't emit `finish` event

### ISSUE THREAD

**Issue by RIAstar** [dominictarr/stream-combiner#13]
Given the following contrived code:

```
    var combiner = require('stream-combiner'),
        through = require('through2');

    return combiner(
        through.obj(pass).on('finish', log('inner stream 1')),
        through.obj(pass).on('finish', log('inner stream 2')),
    ).on('finish', log('combined stream'));

    function pass(file, enc, cb) {
        cb(null, file);
    }

    function log(id) {
        return function() {
            console.log('FINISH: ' + id);
        }
    }
```

and using the returned combined stream in a pipeline, the logged result is as follows:

```
FINISH: inner stream 1
FINISH: inner stream 2
```

Expected result:

```
FINISH: inner stream 1
FINISH: inner stream 2
FINISH: combined stream
```

However, remove one of the inner streams (leaving only one) and you get the expected result:

```
FINISH: inner stream 2
FINISH: combined stream
```

To give this some context: I'm not using `stream-combiner` directly, but as a dependency of [lazypipe](https://github.com/OverZealous/lazypipe), which in turn is a plugin for the [gulp](https://github.com/gulpjs/gulp) build system. Gulp seems to rely on the `finish` event to know when a task is completed, but because it is never fired by the combined stream, the build hangs.

I will create an issue over at `lazypipe` as well, but I'm quite certain that the problem originates here.
https://github.com/OverZealous/lazypipe/issues/14

**Comment by dominictarr** [comment]
try using bun instead, it's designed to be used for streams2 https://www.npmjs.com/package/bun

**Comment by RIAstar** [comment]
Thanks for the suggestion (and sorry for the late reply). 
I'd have to convince the owner of `lazypipe` to move to `bun` though :( or fork it and do it myself (and I'm kind of a rookie when it comes to streams). `bun` itself is a bit too low-level to serve as a Gulp plugin directly.

**Comment by RIAstar** [comment]
It seems I've been barking up the wrong tree :(
The initial issue seems unrelated to the `finish` event after all. See https://github.com/OverZealous/lazypipe/issues/14#issuecomment-89529781 if you care about the details.
